const products = [
  // --- Computer ---
  {
    id: 1,
    name: "Dell OptiPlex 3090 SFF",
    price: 17900,
    quantity: 5,
    description: "Compact desktop for business with Intel performance.",
    category: "computer",
    imageOne: "optic-complex-three-nine-small-two.jpg",
    imageTwo: "optic-complex-three-nine-small-one.jpg",
    imageThree: "optic-complex-three-nine-small-three.jpg",
  },
  {
    id: 2,
    name: "HP EliteDesk 800 G6",
    price: 21500,
    quantity: 7,
    description: "Powerful and secure business desktop PC.",
    category: "computer",
    imageOne: "HP-EliteDesk-800-one.jpg",
    imageTwo: "HP-EliteDesk-800-two.jpg",
    imageThree: "HP-EliteDesk-800-three.jpg",
  },
  {
    id: 3,
    name: "Lenovo ThinkCentre M720",
    price: 18200,
    quantity: 10,
    description: "Reliable desktop with high performance for office tasks.",
    category: "computer",
    imageOne: "lenovo-think-one.webp",
    imageTwo: "lenovo-think-two.webp",
    imageThree: "lenovo-think-three.webp",
  },
  {
    id: 4,
    name: "Acer Veriton S2680G",
    price: 16500,
    quantity: 4,
    description: "Affordable desktop solution with powerful internals.",
    category: "computer",
    imageOne: "acer-veriton-one.jpg",
    imageTwo: "acer-veriton-two.jpg",
    imageThree: "",
  },
  {
    id: 5,
    name: "ASUS ExpertCenter D5",
    price: 20000,
    quantity: 6,
    description: "Stylish business desktop with strong security features.",
    category: "computer",
    imageOne: "ASUS-ExpertCenter-one.png",
    imageTwo: "ASUS-ExpertCenter-two.png",
    imageThree: "ASUS-ExpertCenter-three.png",
  },
  {
    id: 6,
    name: "Intel NUC 11 Essential Kit",
    price: 12900,
    quantity: 9,
    description: "Mini PC with efficient performance and great value.",
    category: "computer",
    imageOne: "Intel-NUC-11-one.webp",
    imageTwo: "Intel-NUC-11-two.webp",
    imageThree: "Intel-NUC-11-three.webp",
  },
  {
    id: 7,
    name: "MSI PRO DP21",
    price: 15800,
    quantity: 8,
    description: "Slim desktop with productivity features.",
    category: "computer",
    imageOne: "MSI-PRO-DP21-one.jpg",
    imageTwo: "MSI-PRO-DP21-two.jpg",
    imageThree: "MSI-PRO-DP21-three.jpg",
  },
  {
    id: 8,
    name: "HP ProDesk 400 G7",
    price: 19400,
    quantity: 3,
    description: "Reliable desktop with robust performance and durability.",
    category: "computer",
    imageOne: "HP-Prodesk-400-G7-one.jpg",
    imageTwo: "HP-Prodesk-400-G7-two.jpg",
    imageThree: "HP-Prodesk-400-G7-three.jpg",
  },
  {
    id: 9,
    name: "Lenovo IdeaCentre 5",
    price: 22000,
    quantity: 2,
    description: "Elegant design with solid hardware for home or office.",
    category: "computer",
    imageOne: "lenovo-desktop-one.jpg",
    imageTwo: "lenovo-desktop-two.jpg",
    imageThree: "lenovo-desktop-three.jpg",
  },
  {
    id: 10,
    name: "Apple Mac Mini M2",
    price: 27900,
    quantity: 4,
    description: "Compact Apple desktop powered by M2 chip.",
    category: "computer",
    imageOne: "TH-Mac-mini-M2-one.jpg",
    imageTwo: "TH-Mac-mini-M2-two.jpg",
    imageThree: "TH-Mac-mini-M2-three.jpg",
  },

  // --- Laptop ---
  {
    id: 11,
    name: "MacBook Air M2",
    price: 42900,
    quantity: 6,
    description: "Lightweight and powerful with Apple M2 chip.",
    category: "laptop",
    imageOne: "MacBook-Air-M2-one.webp",
    imageTwo: "MacBook-Air-M2-two.webp",
    imageThree: "MacBook-Air-M2-three.webp",
  },
  {
    id: 12,
    name: "Dell XPS 13",
    price: 49500,
    quantity: 3,
    description: "Premium ultrabook with infinity-edge display.",
    category: "laptop",
    imageOne: "Dell-Notebook-XPS13-one.webp",
    imageTwo: "Dell-Notebook-XPS13-two.webp",
    imageThree: "Dell-Notebook-XPS13-three.webp",
  },
  {
    id: 13,
    name: "ASUS ROG Zephyrus G14",
    price: 55000,
    quantity: 2,
    description: "High-end gaming laptop with stylish design.",
    category: "laptop",
    imageOne: "ASUS-ROG-Zephyrus-G14-one.jpg",
    imageTwo: "ASUS-ROG-Zephyrus-G14-two.jpg",
    imageThree: "ASUS-ROG-Zephyrus-G14-three.jpg",
  },
  {
    id: 14,
    name: "HP Pavilion 15",
    price: 25000,
    quantity: 8,
    description: "Balanced performance for everyday computing.",
    category: "laptop",
    imageOne: "HP-Pavilion-15-one.webp",
    imageTwo: "HP-Pavilion-15-two.webp",
    imageThree: "HP-Pavilion-15-three.webp",
  },
  {
    id: 15,
    name: "Acer Swift 3",
    price: 21900,
    quantity: 10,
    description: "Portable laptop with excellent battery life.",
    category: "laptop",
    imageOne: "Acer-SWIFT-one.jpg",
    imageTwo: "Acer-SWIFT-two.webp",
    imageThree: "Acer-SWIFT-three.jpg",
  },
  {
    id: 16,
    name: "Lenovo Yoga Slim 7i",
    price: 32000,
    quantity: 5,
    description: "Flexible and sleek ultrabook for professionals.",
    category: "laptop",
    imageOne: "Lenovo-Notebook-Yoga-Slim-7-one.webp",
    imageTwo: "Lenovo-Notebook-Yoga-Slim-7-two.webp",
    imageThree: "Lenovo-Notebook-Yoga-Slim-7-three.webp",
  },
  {
    id: 17,
    name: "MSI Modern 14",
    price: 22500,
    quantity: 4,
    description: "Everyday use laptop with performance and portability.",
    category: "laptop",
    imageOne: "MSI-Modern-14-one.webp",
    imageTwo: "MSI-Modern-14-two.webp",
    imageThree: "MSI-Modern-14-three.webp",
  },

  // --- Accessories ---
  {
    id: 18,
    name: "Logitech MX Master 3S",
    price: 3500,
    quantity: 15,
    description: "Ergonomic wireless mouse with precision control.",
    category: "accessories",
    imageOne: "Logitech-MX-Master-3S-one.webp",
    imageTwo: "Logitech-MX-Master-3S-two.webp",
    imageThree: "Logitech-MX-Master-3S-three.webp",
  },
  {
    id: 19,
    name: "Razer BlackWidow V3",
    price: 4200,
    quantity: 6,
    description: "Mechanical gaming keyboard with RGB lighting.",
    category: "accessories",
    imageOne: "razer-blackwidow-v3-one.jpg",
    imageTwo: "razer-blackwidow-v3-two.jpg",
    imageThree: "razer-blackwidow-v3-three.jpg",
  },
  {
    id: 20,
    name: "Logitech C922 Pro Webcam",
    price: 2800,
    quantity: 9,
    description: "HD webcam ideal for streaming and video calls.",
    category: "accessories",
    imageOne: "Logitech-Webcam-C922-one.webp",
    imageTwo: "Logitech-Webcam-C922-two.webp",
    imageThree: "Logitech-Webcam-C922-three.webp",
  },
];

export default products;
