const products = [
  {
    id: 1,
    name: "Linen Resort Blazer",
    price: 2990,
    quantity: 18,
    description: "Lightweight blazer tailored for warm-weather layering.",
    category: "women",
    imageOne: "women-linen-resort-blazer-1.jpg",
    imageTwo: "women-linen-resort-blazer-2.jpg",
    imageThree: "women-linen-resort-blazer-3.jpg",
  },
  {
    id: 2,
    name: "Silk Midi Slip Dress",
    price: 2450,
    quantity: 22,
    description: "Bias-cut midi dress with elegant movement and shine.",
    category: "women",
    imageOne: "women-silk-midi-slip-dress-1.jpg",
    imageTwo: "women-silk-midi-slip-dress-2.jpg",
    imageThree: "women-silk-midi-slip-dress-3.jpg",
  },
  {
    id: 3,
    name: "Tailored Wide-Leg Trousers",
    price: 1790,
    quantity: 27,
    description: "High-rise trousers with fluid drape and clean silhouette.",
    category: "women",
    imageOne: "women-tailored-trousers-1.jpg",
    imageTwo: "women-tailored-trousers-2.jpg",
    imageThree: "women-tailored-trousers-3.jpg",
  },
  {
    id: 4,
    name: "Pleated Satin Skirt",
    price: 1390,
    quantity: 20,
    description: "Soft pleated skirt designed for versatile day-to-night looks.",
    category: "women",
    imageOne: "women-pleated-satin-skirt-1.jpg",
    imageTwo: "women-pleated-satin-skirt-2.jpg",
    imageThree: "women-pleated-satin-skirt-3.jpg",
  },
  {
    id: 5,
    name: "Cropped Cotton Trench",
    price: 3290,
    quantity: 12,
    description: "Structured cropped trench with detachable waist belt.",
    category: "women",
    imageOne: "women-cropped-cotton-trench-1.jpg",
    imageTwo: "women-cropped-cotton-trench-2.jpg",
    imageThree: "women-cropped-cotton-trench-3.jpg",
  },
  {
    id: 6,
    name: "Knit Polo Dress",
    price: 1590,
    quantity: 24,
    description: "Stretch knit polo dress with minimal chic detailing.",
    category: "women",
    imageOne: "women-knit-polo-dress-1.jpg",
    imageTwo: "women-knit-polo-dress-2.jpg",
    imageThree: "women-knit-polo-dress-3.jpg",
  },
  {
    id: 7,
    name: "Merino Soft Cardigan",
    price: 1690,
    quantity: 30,
    description: "Fine merino cardigan with tonal buttons and slim fit.",
    category: "women",
    imageOne: "women-merino-soft-cardigan-1.jpg",
    imageTwo: "women-merino-soft-cardigan-2.jpg",
    imageThree: "women-merino-soft-cardigan-3.jpg",
  },
  {
    id: 8,
    name: "Relaxed Wool Overshirt",
    price: 2590,
    quantity: 15,
    description: "Textured wool blend overshirt with utility pockets.",
    category: "men",
    imageOne: "men-relaxed-wool-overshirt-1.jpg",
    imageTwo: "men-relaxed-wool-overshirt-2.jpg",
    imageThree: "men-relaxed-wool-overshirt-3.jpg",
  },
  {
    id: 9,
    name: "Minimal Denim Jacket",
    price: 2190,
    quantity: 17,
    description: "Classic denim jacket with modern clean-cut finishing.",
    category: "men",
    imageOne: "men-minimal-denim-jacket-1.jpg",
    imageTwo: "men-minimal-denim-jacket-2.jpg",
    imageThree: "men-minimal-denim-jacket-3.jpg",
  },
  {
    id: 10,
    name: "Pleat Front Chino Pants",
    price: 1490,
    quantity: 29,
    description: "Regular-fit chinos with front pleats for smart styling.",
    category: "men",
    imageOne: "men-pleat-front-chino-1.jpg",
    imageTwo: "men-pleat-front-chino-2.jpg",
    imageThree: "men-pleat-front-chino-3.jpg",
  },
  {
    id: 11,
    name: "Textured Cuban Shirt",
    price: 1290,
    quantity: 26,
    description: "Breathable short-sleeve shirt with resort collar.",
    category: "men",
    imageOne: "men-textured-cuban-shirt-1.jpg",
    imageTwo: "men-textured-cuban-shirt-2.jpg",
    imageThree: "men-textured-cuban-shirt-3.jpg",
  },
  {
    id: 12,
    name: "Layered Hooded Parka",
    price: 3890,
    quantity: 10,
    description: "Water-resistant parka with detachable inner hoodie.",
    category: "men",
    imageOne: "men-layered-hooded-parka-1.jpg",
    imageTwo: "men-layered-hooded-parka-2.jpg",
    imageThree: "men-layered-hooded-parka-3.jpg",
  },
  {
    id: 13,
    name: "Organic Cotton Tee Pack",
    price: 990,
    quantity: 35,
    description: "Set of two premium-weight organic cotton t-shirts.",
    category: "men",
    imageOne: "men-organic-cotton-tee-pack-1.jpg",
    imageTwo: "men-organic-cotton-tee-pack-2.jpg",
    imageThree: "men-organic-cotton-tee-pack-3.jpg",
  },
  {
    id: 14,
    name: "Studio Leather Tote",
    price: 3290,
    quantity: 11,
    description: "Structured tote in smooth leather with magnetic top.",
    category: "bags",
    imageOne: "bag-studio-leather-tote-1.jpg",
    imageTwo: "bag-studio-leather-tote-2.jpg",
    imageThree: "bag-studio-leather-tote-3.jpg",
  },
  {
    id: 15,
    name: "Mini Crossbody Bag",
    price: 1490,
    quantity: 19,
    description: "Compact crossbody with adjustable strap and zip pocket.",
    category: "bags",
    imageOne: "bag-mini-crossbody-1.jpg",
    imageTwo: "bag-mini-crossbody-2.jpg",
    imageThree: "bag-mini-crossbody-3.jpg",
  },
  {
    id: 16,
    name: "Canvas Weekend Duffel",
    price: 2690,
    quantity: 14,
    description: "Large-capacity weekender crafted from waxed canvas.",
    category: "bags",
    imageOne: "bag-canvas-weekend-duffel-1.jpg",
    imageTwo: "bag-canvas-weekend-duffel-2.jpg",
    imageThree: "bag-canvas-weekend-duffel-3.jpg",
  },
  {
    id: 17,
    name: "Chunky Sole Loafers",
    price: 2390,
    quantity: 16,
    description: "Polished leather loafers with elevated chunky sole.",
    category: "shoes",
    imageOne: "shoe-chunky-sole-loafers-1.jpg",
    imageTwo: "shoe-chunky-sole-loafers-2.jpg",
    imageThree: "shoe-chunky-sole-loafers-3.jpg",
  },
  {
    id: 18,
    name: "Retro Runner Sneakers",
    price: 2190,
    quantity: 23,
    description: "Everyday sneakers with breathable mesh and suede trims.",
    category: "shoes",
    imageOne: "shoe-retro-runner-sneakers-1.jpg",
    imageTwo: "shoe-retro-runner-sneakers-2.jpg",
    imageThree: "shoe-retro-runner-sneakers-3.jpg",
  },
  {
    id: 19,
    name: "Square Toe Heels",
    price: 1890,
    quantity: 20,
    description: "Minimal heeled sandals with cushioned footbed support.",
    category: "shoes",
    imageOne: "shoe-square-toe-heels-1.jpg",
    imageTwo: "shoe-square-toe-heels-2.jpg",
    imageThree: "shoe-square-toe-heels-3.jpg",
  },
  {
    id: 20,
    name: "Soft Ballet Flats",
    price: 1290,
    quantity: 28,
    description: "Foldable ballet flats with padded insole and bow detail.",
    category: "shoes",
    imageOne: "shoe-soft-ballet-flats-1.jpg",
    imageTwo: "shoe-soft-ballet-flats-2.jpg",
    imageThree: "shoe-soft-ballet-flats-3.jpg",
  },
];

export default products;
